package com.example.model;
// Generated Apr 30, 2019 11:52:28 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Address generated by hbm2java
 */
public class Address implements java.io.Serializable {

	private Integer id;
	private String city;
	private String street;
	private String lane;
	private String houseNumber;
	private Set postses = new HashSet(0);
	private Set users = new HashSet(0);

	public Address() {
	}

	public Address(String city, String street, String lane, String houseNumber) {
		this.city = city;
		this.street = street;
		this.lane = lane;
		this.houseNumber = houseNumber;
	}

	public Address(String city, String street, String lane, String houseNumber, Set postses, Set users) {
		this.city = city;
		this.street = street;
		this.lane = lane;
		this.houseNumber = houseNumber;
		this.postses = postses;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getLane() {
		return this.lane;
	}

	public void setLane(String lane) {
		this.lane = lane;
	}

	public String getHouseNumber() {
		return this.houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber;
	}

	public Set getPostses() {
		return this.postses;
	}

	public void setPostses(Set postses) {
		this.postses = postses;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
