package com.example.model;
// Generated Apr 30, 2019 11:52:28 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Apartment generated by hbm2java
 */
public class Apartment implements java.io.Serializable {

	private int id;
	private Category category;
	private int area;
	private Set postses = new HashSet(0);

	public Apartment() {
	}

	public Apartment(int id, Category category, int area) {
		this.id = id;
		this.category = category;
		this.area = area;
	}

	public Apartment(int id, Category category, int area, Set postses) {
		this.id = id;
		this.category = category;
		this.area = area;
		this.postses = postses;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	public Set getPostses() {
		return this.postses;
	}

	public void setPostses(Set postses) {
		this.postses = postses;
	}

}
