package com.example.model;
// Generated Apr 30, 2019 11:52:28 AM by Hibernate Tools 5.2.12.Final

/**
 * Posts generated by hbm2java
 */
public class Posts implements java.io.Serializable {

	private Integer id;
	private Address address;
	private Apartment apartment;
	private User user;
	private String titile;
	private String content;
	private String img;
	private String startAt;
	private int status;
	private double price;

	public Posts() {
	}

	public Posts(Address address, Apartment apartment, User user, String titile, String content, String img,
			String startAt, int status, double price) {
		this.address = address;
		this.apartment = apartment;
		this.user = user;
		this.titile = titile;
		this.content = content;
		this.img = img;
		this.startAt = startAt;
		this.status = status;
		this.price = price;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public Apartment getApartment() {
		return this.apartment;
	}

	public void setApartment(Apartment apartment) {
		this.apartment = apartment;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getTitile() {
		return this.titile;
	}

	public void setTitile(String titile) {
		this.titile = titile;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String getStartAt() {
		return this.startAt;
	}

	public void setStartAt(String startAt) {
		this.startAt = startAt;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
