package com.example.model;
// Generated Apr 30, 2019 11:52:28 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Address address;
	private String name;
	private int idNumber;
	private int type;
	private int phone;
	private String avt;
	private String startAt;
	private String email;
	private Set postses = new HashSet(0);

	public User() {
	}

	public User(Address address, String name, int idNumber, int type, int phone, String avt, String startAt,
			String email) {
		this.address = address;
		this.name = name;
		this.idNumber = idNumber;
		this.type = type;
		this.phone = phone;
		this.avt = avt;
		this.startAt = startAt;
		this.email = email;
	}

	public User(Address address, String name, int idNumber, int type, int phone, String avt, String startAt,
			String email, Set postses) {
		this.address = address;
		this.name = name;
		this.idNumber = idNumber;
		this.type = type;
		this.phone = phone;
		this.avt = avt;
		this.startAt = startAt;
		this.email = email;
		this.postses = postses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(int idNumber) {
		this.idNumber = idNumber;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	public String getAvt() {
		return this.avt;
	}

	public void setAvt(String avt) {
		this.avt = avt;
	}

	public String getStartAt() {
		return this.startAt;
	}

	public void setStartAt(String startAt) {
		this.startAt = startAt;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getPostses() {
		return this.postses;
	}

	public void setPostses(Set postses) {
		this.postses = postses;
	}

}
