package com.example.model;
// Generated May 1, 2019 10:15:11 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", catalog = "bookingroom")
public class Address implements java.io.Serializable {

	private Integer id;
	private String city;
	private String street;
	private String lane;
	private String houseNumber;
	private Set<Posts> postses = new HashSet<Posts>(0);
	private Set<User> users = new HashSet<User>(0);

	public Address() {
	}

	public Address(String city, String street, String lane, String houseNumber) {
		this.city = city;
		this.street = street;
		this.lane = lane;
		this.houseNumber = houseNumber;
	}

	public Address(String city, String street, String lane, String houseNumber, Set<Posts> postses, Set<User> users) {
		this.city = city;
		this.street = street;
		this.lane = lane;
		this.houseNumber = houseNumber;
		this.postses = postses;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "city", nullable = false, length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "street", nullable = false, length = 100)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "lane", nullable = false, length = 100)
	public String getLane() {
		return this.lane;
	}

	public void setLane(String lane) {
		this.lane = lane;
	}

	@Column(name = "house_number", nullable = false, length = 20)
	public String getHouseNumber() {
		return this.houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Posts> getPostses() {
		return this.postses;
	}

	public void setPostses(Set<Posts> postses) {
		this.postses = postses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
