package com.example.model;
// Generated May 1, 2019 10:15:11 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Apartment generated by hbm2java
 */
@Entity
@Table(name = "apartment", catalog = "bookingroom")
public class Apartment implements java.io.Serializable {

	private int id;
	private Category category;
	private int area;
	private Set<Posts> postses = new HashSet<Posts>(0);

	public Apartment() {
	}

	public Apartment(int id, Category category, int area) {
		this.id = id;
		this.category = category;
		this.area = area;
	}

	public Apartment(int id, Category category, int area, Set<Posts> postses) {
		this.id = id;
		this.category = category;
		this.area = area;
		this.postses = postses;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "type", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "area", nullable = false)
	public int getArea() {
		return this.area;
	}

	public void setArea(int area) {
		this.area = area;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "apartment")
	public Set<Posts> getPostses() {
		return this.postses;
	}

	public void setPostses(Set<Posts> postses) {
		this.postses = postses;
	}

}
