package com.example.model;
// Generated May 1, 2019 10:15:11 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "bookingroom")
public class User implements java.io.Serializable {

	private Integer id;
	private Address address;
	private String name;
	private int idNumber;
	private int type;
	private int phone;
	private String avt;
	private String startAt;
	private String email;
	private Set<Posts> postses = new HashSet<Posts>(0);

	public User() {
	}


	public User(Integer id, Address address, String name, int idNumber, int type, int phone, String avt, String startAt,
			String email, Set<Posts> postses) {
		this.id=id;
		this.address = address;
		this.name = name;
		this.idNumber = idNumber;
		this.type = type;
		this.phone = phone;
		this.avt = avt;
		this.startAt = startAt;
		this.email = email;
		this.postses = postses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id_number", nullable = false)
	public int getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(int idNumber) {
		this.idNumber = idNumber;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "phone", nullable = false)
	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	@Column(name = "avt", nullable = false, length = 100)
	public String getAvt() {
		return this.avt;
	}

	public void setAvt(String avt) {
		this.avt = avt;
	}

	@Column(name = "start_at", nullable = false, length = 50)
	public String getStartAt() {
		return this.startAt;
	}

	public void setStartAt(String startAt) {
		this.startAt = startAt;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Posts> getPostses() {
		return this.postses;
	}

	public void setPostses(Set<Posts> postses) {
		this.postses = postses;
	}

}
